# Generated by Django 5.0.7 on 2024-07-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authorizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Verifying', 'verifying'), ('Active', 'active'), ('Suspended', 'suspended'), ('Baned', 'baned')], max_length=50)),
            ],
        ),
    ]
