# Generated by Django 5.0.7 on 2024-07-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_expire_user_v_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='v_code',
        ),
    ]
