# Generated by Django 5.0.7 on 2024-07-17 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='dependency',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_mobile',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='pre',
            field=models.CharField(default='98', max_length=4, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='pre'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='No',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='No'),
        ),
    ]
