# Generated by Django 5.0.7 on 2024-07-20 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phone_expire_phone_v_code_alter_phone_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='No',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='No'),
        ),
    ]
