# Generated by Django 5.0.7 on 2024-07-14 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('s+', 'S+'), ('s', 'S'), ('a+', 'A+'), ('a', 'A'), ('b+', 'B+'), ('b', 'B'), ('l', 'L')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.JSONField(blank=True, default=list)),
                ('vids', models.JSONField(blank=True, default=list)),
                ('length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('not_available', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mines.mine')),
                ('mtr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mines.material')),
                ('ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.color')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.quality')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.schema')),
            ],
        ),
    ]
