# Generated by Django 5.0.6 on 2024-05-20 17:52

import blocks.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('not_available', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('s+', 'S+'), ('s', 'S'), ('a+', 'A+'), ('a', 'A'), ('b+', 'B+'), ('b', 'B'), ('l', 'L')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlockPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, default='img/no-pic.png', upload_to=blocks.models.blockPicPath, verbose_name='Image')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block')),
            ],
        ),
        migrations.CreateModel(
            name='BlockVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.city')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.city'),
        ),
        migrations.AddField(
            model_name='block',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.material'),
        ),
        migrations.AddField(
            model_name='block',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.quality'),
        ),
        migrations.AddField(
            model_name='block',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.schema'),
        ),
    ]
