# Generated by Django 5.0.6 on 2024-05-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
