# Generated by Django 5.0.6 on 2024-05-20 18:01

from django.db import migrations
from blocks.models import Quality, GRADES


def set_quality_grades(apps, schema_editor):
    # Quality = apps.get_model("apps", "Quality")
    for grade in GRADES:
        # instance = Quality.objects.create(grade=grade[0])
        Quality.objects.create(grade=grade[0])


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_quality_grades),
    ]

