# Generated by Django 5.0.6 on 2024-06-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20240520_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='pics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='block',
            name='vids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
