# Generated by Django 5.0.7 on 2024-07-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_quality_seeder'),
        ('cities', '0001_initial'),
        ('mines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='ct',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
        migrations.AlterField(
            model_name='block',
            name='mtr',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mines.material'),
        ),
    ]
