# Generated by Django 5.0.6 on 2024-05-20 18:11

import blocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20240520_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpic',
            name='pic',
            field=models.ImageField(blank=True, default='no-pic.png', upload_to=blocks.models.blockPicPath, verbose_name='Image'),
        ),
    ]
