# Generated by Django 5.0.6 on 2024-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_alter_block_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='grade',
            field=models.CharField(choices=[('s+', 'S+'), ('s', 'S'), ('a+', 'A+'), ('a', 'A'), ('b+', 'B+'), ('b', 'B'), ('l', 'L')], max_length=2),
        ),
    ]
