# Generated by Django 5.0.6 on 2024-05-21 05:36

import blocks.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_alter_blockpic_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockvid',
            name='vid',
            field=models.FileField(default=None, upload_to=blocks.models.blockVidPath),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockvid',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block'),
        ),
    ]
