# Generated by Django 5.0.6 on 2024-07-13 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_block_pics_block_vids'),
        ('mines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='city',
        ),
        migrations.RemoveField(
            model_name='block',
            name='material',
        ),
        migrations.AddField(
            model_name='block',
            name='mine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mines.mine'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
