# Generated by Django 5.0.7 on 2024-07-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_alter_block_ct_alter_block_mtr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Available', 'available'), ('Ordered', 'ordered'), ('Sold', 'sold')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='block',
            name='not_available',
        ),
    ]
