# Generated by Django 5.0.6 on 2024-05-20 18:01

from django.db import migrations
from blocks.models import Availability, statuses


def seed_availability(apps, schema_editor):
    # Availability = apps.get_model("apps", "Availability")
    for status in statuses:
        # instance = Availability.objects.create(status=status[0])
        Availability.objects.create(status=status[0])


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_availability_remove_block_not_available'),
    ]

    operations = [
        migrations.RunPython(seed_availability),
    ]

