# Generated by Django 5.0.6 on 2024-07-13 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_remove_block_city_remove_block_material_block_mine_and_more'),
        ('mines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='mine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mines.mine'),
        ),
    ]
