# Generated by Django 5.0.6 on 2024-05-17 16:32

from django.db import migrations
from blocks.models import Quality, GRADES


def set_quality_grades(apps, schema_editor):
    # Quality = apps.get_model("apps", "Quality")
    for grade in GRADES:
        instance = Quality.objects.create(grade=grade[0])


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_alter_quality_grade'),
    ]

    operations = [
        migrations.RunPython(set_quality_grades),
    ]
