# Generated by Django 5.0.6 on 2024-07-13 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_alter_block_mine'),
        ('mines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mines.mine'),
        ),
    ]
