# Generated by Django 5.0.7 on 2024-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_block_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
