# Generated by Django 5.0.7 on 2024-07-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0001_initial'),
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Verifying', 'verifying'), ('Active', 'active'), ('Paused', 'paused'), ('Closed', 'closed'), ('Baned', 'baned')], max_length=50)),
            ],
        ),
    ]
