# Generated by Django 5.0.7 on 2024-07-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0003_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='activity',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mines.activity'),
        ),
    ]
