# Generated by Django 5.0.7 on 2024-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0006_minestaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Hired', 'hired'), ('Absent', 'absent'), ('Suspended', 'suspended'), ('Fired', 'fired')], max_length=50)),
            ],
        ),
    ]
