# Generated by Django 5.0.6 on 2024-06-18 23:08

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pic',
            field=models.ImageField(upload_to=files.models.pic_path, verbose_name='Image'),
        ),
    ]
