# Generated by Django 5.0.6 on 2024-05-20 18:01

from django.db import migrations
from factories.models import StaffActivity, staff_statuses


def seed_activity(apps, schema_editor):
    # StaffActivity = apps.get_model("apps", "StaffActivity")
    for status in staff_statuses:
        # instance = StaffActivity.objects.create(status=status[0])
        StaffActivity.objects.create(status=status[0])


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0004_staffactivity'),
    ]

    operations = [
        migrations.RunPython(seed_activity),
    ]

