# Generated by Django 5.0.7 on 2024-07-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0006_factorystaff_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factorystaff',
            old_name='mine',
            new_name='factory',
        ),
    ]
